import type { AuditEventName } from '$lib/server/audit/events';

export const EVENT_TEXT: Record<AuditEventName, string> = {
	'restaurant.registered': 'Restaurant registered',
	'user.created': 'Account created',
	'login.success': 'Signed in',
	'login.failed': 'Failed sign-in attempt',
	'login.locked_out': 'Account locked after repeated failures',
	'login.rejected_locked': 'Sign-in refused while locked',
	logout: 'Signed out',
	'settings.updated': 'Settings changed',
	'user.password_reset_by_operator': 'Password reset from the command line',
	'pos.device.registered': 'POS device registered',
	'pos.device.revoked': 'POS device revoked',
	'pos.pin.success': 'Signed in at the POS',
	'pos.pin.failed': 'Failed POS sign-in attempt',
	'pos.pin.locked_out': 'Employee locked out at the POS after repeated failures',
	'employee.created': 'Employee added',
	'employee.pin_set': 'Employee PIN set',
	'employee.updated': 'Employee changed',
	'employee.deactivated': 'Employee deactivated',
	'employee.reactivated': 'Employee reactivated',
	'employee.lockout_cleared': 'Employee PIN lockout cleared',
	'role.created': 'Role created',
	'role.updated': 'Role changed',
	'role.archived': 'Role archived',
	'menu.price_changed': 'Menu price changed',
	'pos.session.opened': 'Shift opened on the till',
	'pos.session.closed': 'Shift closed and drawer counted',
	'sale.recorded': 'Sale recorded',
	'sale.flagged': 'Sale recorded with a flag for review',
	'sale.abandoned': 'Sale abandoned; its invoice number was burned',
	'sync.op_unrecorded': 'A synced operation could not be recorded and needs review',
	'sync.op_retried': 'Flagged operation retried',
	'sync.op_dismissed': 'Flagged operation dismissed',
	'pos.pin.offline_success': 'Signed in at the POS while offline',
	'pos.pin.offline_failed': 'Failed POS sign-in attempt while offline',
	'ingredient.created': 'Ingredient added',
	'ingredient.updated': 'Ingredient changed',
	'ingredient.archived': 'Ingredient archived',
	'purchase_unit.added': 'Purchase unit added to an ingredient',
	'purchase_unit.archived': 'Purchase unit archived',
	'recipe.changed': 'Recipe changed',
	'purchase.recorded': 'Recorded a delivery',
	'purchase.reversed': 'Reversed a delivery',
	'supplier.paid': 'Paid a supplier',
	'supplier.payment_reversed': 'Reversed a supplier payment',
	'waste.recorded': 'Recorded waste',
	'stock.counted': 'Posted a stock count',
	'opening_stock.recorded': 'Recorded opening stock',
	'tax_rate.created': 'Tax rate added',
	'tax_rate.updated': 'Tax rate changed',
	'tax_rate.archived': 'Tax rate archived'
};
