import { sql } from 'drizzle-orm';
import {
	pgTable,
	uuid,
	text,
	bigint,
	date,
	timestamp,
	index,
	uniqueIndex,
	unique,
	check
} from 'drizzle-orm/pg-core';
import { restaurants } from './restaurants';
import { posDevices } from './pos-devices';
import { users } from './users';

// SPEC 10: a POS session is a cashier shift, distinct from the auth session.
// It holds the opening float, and at close: the counted cash, the expected
// cash (opening float + Σ cash payments of the session's recorded orders —
// refunds, pay-ins and pay-outs are zero in this plan) and difference =
// counted − expected, which T-20 posts as Dr 6800 Cash Over/Short / Cr 1000
// Cash on Hand when negative and Dr 1000 / Cr 6800 when positive (nothing
// when zero).
//
// INVARIANT 11 — business_date is THE business date of every sale in this
// session; T-20 derives it IN SQL from opened_at in the restaurant's time zone
// ((opened_at at time zone <tz>)::date), never in JavaScript. Reports GROUP BY
// this column, never by created_at::date.
//
// The row `id` is generated by the DEVICE (the session.open op carries it);
// defaultRandom() exists only so a direct test insert works.
//
// opened_at is the device's occurredAt; received_at is when the server stored
// the row. closed_from_device_id exists for DEVICE LINEAGE: after a revoke-
// and-re-register the successor device (the cookie's live device) may close
// a session that an older, now revoked device opened; device_id stays the
// opener.
//
// The close fields (closed_at, closed_by_user_id, closed_from_device_id,
// counted_cash_minor, expected_cash_minor, difference_minor, status) are
// written ONCE, by closeSession (T-20), in the same transaction as the
// over/short entry; pos_sessions_closed_fields requires ALL of them together
// when status = 'closed' — closed_from_device_id included, because
// closeSession always sets it and a closed session with no device lineage is
// a row the database must refuse. A session is not one of invariant 2's
// posted records, but nothing else may update it and no code path reopens
// a closed session.

const tenant = () =>
	uuid('restaurant_id')
		.notNull()
		.references(() => restaurants.id, { onDelete: 'restrict' });
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

export const posSessions = pgTable(
	'pos_sessions',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		restaurantId: tenant(),
		deviceId: uuid('device_id')
			.notNull()
			.references(() => posDevices.id, { onDelete: 'restrict' }),
		openedByUserId: uuid('opened_by_user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'restrict' }),
		openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
		receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
		businessDate: date('business_date', { mode: 'string' }).notNull(),
		openingCashMinor: bigint('opening_cash_minor', { mode: 'bigint' }).notNull(),
		status: text('status').notNull(),
		closedAt: timestamp('closed_at', { withTimezone: true }),
		closedByUserId: uuid('closed_by_user_id').references(() => users.id, { onDelete: 'restrict' }),
		closedFromDeviceId: uuid('closed_from_device_id').references(() => posDevices.id, {
			onDelete: 'restrict'
		}),
		countedCashMinor: bigint('counted_cash_minor', { mode: 'bigint' }),
		expectedCashMinor: bigint('expected_cash_minor', { mode: 'bigint' }),
		differenceMinor: bigint('difference_minor', { mode: 'bigint' }),
		createdAt: createdAt()
	},
	(t) => [
		// Target of orders_session_fk — a UNIQUE CONSTRAINT, not an index.
		unique('pos_sessions_id_restaurant_unique').on(t.id, t.restaurantId),
		// One open session per device (spec 10). Partial, so closed sessions pile up freely.
		uniqueIndex('pos_sessions_one_open_per_device')
			.on(t.deviceId)
			.where(sql`${t.status} = 'open'`),
		index('pos_sessions_restaurant_business_date_idx').on(t.restaurantId, t.businessDate),
		index('pos_sessions_device_status_idx').on(t.deviceId, t.status),
		check('pos_sessions_opening_cash_non_negative', sql`${t.openingCashMinor} >= 0`),
		check('pos_sessions_status_valid', sql`${t.status} in ('open', 'closed')`),
		check(
			'pos_sessions_closed_fields',
			sql`((${t.status} = 'closed') = (${t.closedAt} is not null)) and (${t.status} = 'open' or (${t.countedCashMinor} is not null and ${t.expectedCashMinor} is not null and ${t.differenceMinor} is not null and ${t.closedByUserId} is not null and ${t.closedFromDeviceId} is not null))`
		)
	]
);
